# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.

# Main Page Setup
title: MD MARUF AHMED
baseurl: "" # Leave this empty since your site is at the root

# Hero Section
name: MD MARUF AHMED
headline: Aerospace Engineering Student
description: >-
  Passionate aerospace engineering student with a strong foundation in CAD, prototyping, and design standards.

# Place your profile image in /assets/images/profile-image/folder and edit the file name
profile_image: ./assets/images/profile-image/avatar.jpeg

# Link your resume
resume-url: https://drive.google.com/file/d/13Z3duVzh-gguPU5r03oJVEE6rV9rd3DS/view?usp=sharing

# Set up external links
external-links:
  linkedin: your-linkedin-username
  github: maruf066

# Skills Section
skills:
  - category: 3D Modeling
    tools:
    - Onshape
    - Solidworks
    - Creo
    - Fusion 360 (Autodesk)
    - Siemens NX
  - category: Prototyping
    tools:
    - SLA
    - CNC
    - FDM
    - 3D Printing
  - category: Problem Solving
    tools:
    - Root Cause Analysis
    - Six Sigma

# Active theme
colors:
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

# Build settings
collections:
  projects:
    output: true
    permalink: /projects/:path/

markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
include:
  - _projects
